### ISSUE TITLE
Suggested new source: Getlost Maps (Australia)

### ISSUE THREAD

**Issue by Ferretdog** [johanberonius/custom-map-source.appspot.com#4]
https://live.getlost.com.au/apps/galileo-getlost_maps-2x.png

galileo-getlost-maps.ms
```
<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
    <name>Getlost Maps</name>
    <minZoom>10</minZoom>
    <maxZoom>16</maxZoom>
    <url>https://live.getlost.com.au/{$z}/{$x}/{$y}.jpg</url>
</customMapSource>


```

**Comment by johanberonius** [comment]
Added Getlost Maps for Australia.

Updated now at https://git.beroni.us/custom-map-source.appspot.com/ (but not yet at https://custom-map-source.appspot.com/ due to Google Cloud issues)

Note for Safari on iOS: You must long touch and select "Download linked file" to save a map source and then open it using Guru Maps.
